# A. Arrays

In [1]:
import numpy as np
arr = np.array([-1, 2, 5], dtype = np.float32)
print(repr(arr)) # it prints array with its datatype
print(arr) # it prints only array

array([-1.,  2.,  5.], dtype=float32)
[-1.  2.  5.]


In [5]:
arr1 = np.array([2,6,3,2,32])
print(repr(arr1)) # all elements consider as int32 (32 means 32 bit) 
print(arr1.dtype)

array([ 2,  6,  3,  2, 32])
int32


In [6]:
arr2 = np.array([2,3334,5.67,43.76,324]) # it contains some integer and some float
print(repr(arr2))
print(arr2.dtype) # all the elements considered as float64 (64 means 64 bit)

array([2.000e+00, 3.334e+03, 5.670e+00, 4.376e+01, 3.240e+02])
float64


In [7]:
arr3 = np.array(["name","animal","jungle","sky"])
print(repr(arr3))
print(arr3.dtype) # all are considered as string

array(['name', 'animal', 'jungle', 'sky'], dtype='<U6')
<U6


In [2]:
# what is the type of numpy array if python list have elements of more than one datatype

arr4 = np.array([1,4,"name",5.346,34534,'A']) # all will consider as string
print(repr(arr4))
print(arr4.dtype) 

array(['1', '4', 'name', '5.346', '34534', 'A'], dtype='<U32')


# B. Copying

In [8]:
a = np.array([4,7]) 
b = np.array([2,9]) 
c = a # here (c) is not a copy of (a), it is another name of (a) or reference of (a)
# so if we change the value of (c) that means we are changing the value of (a)
print('Array a: {}', format(repr(a)))
print("Array c:",c)
c[0] = 12
print("Array a:",a)
print("Array c:",c)

d = b.copy() # here we make a new array (d) which is a copy of array (b)
print("Array b:",b)
print("Array d:",d)
d[0] = 55
print("Array b:",b)
print("Array d:",d)


Array a: {} array([4, 7])
Array c: [4 7]
Array a: [12  7]
Array c: [12  7]
Array b: [2 9]
Array d: [2 9]
Array b: [2 9]
Array d: [55  9]


# C. Casting

In [9]:
# changing of datatype
arr = np.array([1,2,3])
print(arr.dtype) # it's type is int at this time
arr = arr.astype(np.float32) # here we use astype function to change it's datatype to float32
print(arr.dtype)

int32
float32


# D. NaN

In [10]:
# when we don't want a numpy array to contain a value at a particular index, we can use np.nan to act as a placeholder
arr = np.array([np.nan, 23,"name",34.34])
print(arr) # it prints (nan) at index 0
arr[0] = 55
print(arr) # it prints 55 at index 0
# we can't do typecasting here because the unknown quantity will be int, float or string 

['nan' '23' 'name' '34.34']
['55' '23' 'name' '34.34']


# E. Infinity

In [11]:
# to represent infinity in numpy, we use the np.inf special value. We can also represent negative infinity with -np.inf
print(np.inf > 10009099909090)
arr = np.array([np.inf, 345,432])
print(arr)
# here we can't do typecasting to int because the infinity will not come in range of int

True
[ inf 345. 432.]
