In [1]:
import numpy as np

# A. Ranged data

In [4]:
# it only prints with a gap of 1 

arr = np.arange(5) # it prints 0,1,2,3,4 (means less than the value written in brackets)
print(repr(arr))

arr = np.arange(5.1) # it prints (0., 1., 2., 3., 4., 5.) (means less than the value written in brackets)
print(repr(arr))

arr = np.arange(-1,4) # it starts from -1 and stops before range, so prints (-1,0,1,2,3)
print(repr(arr))

arr = np.arange(-1.5,4,2) # it starts printing from -1.5 to a range of 4 with a gap of 2 so prints (-1.5, 0.5, 2.5)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [6]:
lspace = np.linspace(1,5,12) # this function is little hard to understand
# so here in the above line we can see three number (1,5,12), this function makes total of 12 numbers such that first number is 
# (1), last number is (5) and the difference between a number and it's previous one is same for all. Let's take some examples
print(lspace)
l2space = np.linspace(1,4,4) # so it makes total of 4 numbers starts from (1) and ends at (4) and gap between every two consecutive is equal 
# so output when print --> 1., 2., 3., 4.
print(l2space)
l3space = np.linspace(1,4,7) # so it makes total of 7 numbers starts from (1) and ends at (4) and gap between every two consecutive is equal
# so output when print --> 1., 1.5, 2., 2.5, 3., 3.5, 4.
print(l3space)
l4space = np.linspace(1,4,4, endpoint = False) # by making endpoint = False the endpoint (means 4) is now not included
# so now it breaks it in 4 parts with equal gap without including the 4
print(l4space)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]
[1. 2. 3. 4.]
[1.  1.5 2.  2.5 3.  3.5 4. ]
[1.   1.75 2.5  3.25]


# B. Reshaping data

In [ ]:
arr5 = np.arange(240)
print(arr5.reshape(16,15)) # makes a 2d matrix of size 16x15
# the size of matrix must cover all the elements of the array
print(arr5.reshape(5,6,8)) # it prints a 3d matrix of size 5x6x8
print(arr5.reshape(2,4,5,6)) # it makes a 4d matrix of size 2x4x5x6
# if i don't know the factors of 240 to reshape it then i use -1 in one of those place where i don't know
print(arr5.reshape(5,-1,8)) # it prints a 3d matrix of size 5x6x8 
# (it takes 6 automatically at place of -1 because only 6 completes the requirement to complete the product equal to 240 )

In [20]:
# in order to regain the initial 1d shape of array after reshaping it at by above method we use this 
arr = np.arange(8)
arr = np.reshape(arr, (2,4)) # this is another format of reshaping
flattened = arr.flatten() # arr is now flattened in 1d array
print(repr(arr))
print('arr shape: {}'. format(arr.shape))
print(repr(flattened))
print('flattened shape: []'. format(flattened.shape))
# .flatten makes a copy because of which the shape of original one remains changed and not become flat

# another function (ravel) to regain the initial (1d array)
arr = np.reshape(arr, (2,4))
print(repr(arr))
arr = arr.ravel()
print(arr)

# one more function (flat) to regain the initial 1d shape
arr = np.reshape(arr, (2,4))
print(repr(arr))
for i in arr.flat: # flat prints in another way
    print(i,end = " ") 


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: []
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
[0 1 2 3 4 5 6 7]
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
0 1 2 3 4 5 6 7 

# C. Transpose

In [22]:
x = [[5,4,6], [7,9,8], [3,2,1]]
ar = np.array(x)
print(ar)
print(ar.T) # it prints the transpose of the array , it is an attribute
# and another function is 
print(np.transpose(ar)) # this is a function 

[[5 4 6]
 [7 9 8]
 [3 2 1]]
[[5 7 3]
 [4 9 2]
 [6 8 1]]
[[5 7 3]
 [4 9 2]
 [6 8 1]]


In [24]:
arr = np.arange(24)
arr = np.reshape(arr, (3,4,2))
# transposing decided by the axes
transposed = np.transpose(arr, axes = (1, 2, 0))
# in the above line we transpose it in our suitable way (1,2,0) means pattern (3,4,2) becomes (4,2,3)
# index 0 is filled by a number which is at index 1 = (4), index 1 is filled by a number which is at index 2 = (2), index 2 is filled by a number which is at index 0 = (3)
# so the pattern will be --> total 4 sets, each set contains 2 list, each list contains 3 elements
print(arr)
print(transposed)
print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[ 0  8 16]
  [ 1  9 17]]

 [[ 2 10 18]
  [ 3 11 19]]

 [[ 4 12 20]
  [ 5 13 21]]

 [[ 6 14 22]
  [ 7 15 23]]]
arr shape: (3, 4, 2)
transposed shape: (4, 2, 3)


# D. Zeros and ones

In [25]:
arr0Ka = np.zeros((4,5)) # it makes a 2d array in which 2nd dimension contains 4 elements and 1st dimension contains 5 elements and all elements of 1st dimension is 1 [matrix 4x5]
arr1Ka = np.ones(((2,4,6))) # it makes a 3d array in which 3rd dimension contains 2 elements, 2nd dimension contains 4 elements and 1st dimension contains 6 elements and all elements of 1st dimesion is 1 [matrix 2x4x6]
print(arr0Ka)
print(arr1Ka)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


In [26]:
arr = np.array([[1,2], [3,4]])
print(repr(np.zeros_like(arr))) # it prints an array of 0 in the format of (arr) array


array([[0, 0],
       [0, 0]])


In [30]:
arr = np.zeros(5)
print(arr)
temp = np.reshape(arr, (1,5))
print(temp)
arr2 = np.ones_like(np.transpose(temp))
print(arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
