In [2]:
import numpy as np

# A. Arithmetic

In [3]:
arr = np.array([[1,2], [3,4]])
# add 1 to element values
print(repr(arr + 1))
# subtract element values by 1.2
print(repr(arr - 1.2))
# double element values
print(repr(arr * 2))
# half element values
print(repr(arr / 2))
# integer division (half)
print(repr(arr // 2)) # this type of division prints only integer value and not show fractional part
# square element values
print(repr(arr ** 2))
# square root element values
print(repr(arr ** 0.5))

array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]], dtype=int32)
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [4]:
# we could convert a dataset of Fahrenhiet temparatures to their equivalent Celcius form
def f2c(temps):
    return (5/9)*(temps - 32)

fahrenheits = np.array([32, -4,14, -40])
celcius = f2c (fahrenheits)
print(f"the array of celcius temparature is: {celcius}")

the array of celcius temparature is: [  0. -20. -10. -40.]


# B. Non-linear function

In [13]:
arr = np.array([[1,2], [3,4]])

# raised to power of e
print(repr(np.exp(arr)))
# raised to power of 2
print(repr(np.exp2(arr)))
# np.e represents the constant (e) , np.pi represents the constant (3.14,pi)
arr2 = np.array([[1,10], [np.e,np.pi]]) 
print(arr2)
# natural logarithm
print(repr(np.log(arr2)))
# base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
[[ 1.         10.        ]
 [ 2.71828183  3.14159265]]
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [6]:
# to do a regular power operation with any base, we use np.power. The first argument to the function is the base,
# while the second is the power. If the base or power is an array rather than a single number,
# the operation is applied to every element in the array.
arr =np.array([[1,2],[3,4]])
# raise 3 to power of each number in arr
print(repr(np.power(3,arr)))
arr2 = np.array([[10.2,4], [3,5]])
# raise arr2 to power of each numberin arr
print(repr(np.power(arr2,arr))) 

array([[ 3,  9],
       [27, 81]], dtype=int32)
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


# C. Matrix multiplication

In [12]:
# when both matrices are 1d then their multiplication is the dot product
# Note that the dimensions of the two input matrices must be valid for a matrix multiplication.
# Specifically, the second dimension(no. of columns) of the first matrix must equal to the first dimension(no. of rows) of the second matrix other np.matmul will result in value error

arr1 = np.array([1,2,3])
arr2 = np.array([-3,0,10])
print(np.matmul(arr1,arr2))

arr3 = np.array([[1,2], [3,4], [5,6]]) # here number of columns is 2
arr4 = np.array([[-1,0,1,2], [3,2,-4,2]]) # here number of rows is 2 
print(arr3)
print(arr4)
print(repr(np.matmul(arr3,arr4)))

# The below line will show error if uncomment it
# print(repr(np.matmul(arr4, arr3))) # because number of columns of arr4(4) is not equal to the number of rows of arr3(3)

27
[[1 2]
 [3 4]
 [5 6]]
[[-1  0  1  2]
 [ 3  2 -4  2]]
array([[  5,   4,  -7,   6],
       [  9,   8, -13,  14],
       [ 13,  12, -19,  22]])
