In [2]:
import numpy as np

# A. Random integers

In [10]:
# np.ranodm generates a random number while np.random.randint generates a random integer

print(np.random.randint(5)) # it prints a random integer in range [0,5) (5 is excluded)
print(np.random.randint(5)) # it prints a random integer in range [0,5) (5 is excluded)
print(np.random.randint(5, high = 10)) # it prints a random integer in range [5,10) (10 is excluded) 

random_arr = np.random.randint(-3, high=14, size=(2,2)) # it makes a matrix or array of size 2x2 in which every number is in range [-3,14)
print(repr(random_arr))
print(np.random.randint(5, high = None)) # in this case the upper argument will become 5 and lower argument 0 --> range [0,5)

0
3
7
array([[8, 7],
       [8, 0]])
3


# B. Utility functions 

In [17]:
# by using (np.random)
# (np.random.seed) function allows us to set the random seed, which allows us to control the outputs of the pseudo-random functions
# the function takes in a single integer as an argument, representing the random seed.
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2,2))
print(repr(random_arr))

# new seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2,2))
print(repr(random_arr))

# original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2,2))
print(repr(random_arr))

# the output of 1st and 3rd are same because we set seed equal to 1 for both but there is condition that the same seed array also have same low,high,size
# or another use of this is that no matter how many times you run it, it will give the same output if we set a seed before


5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


In [18]:
# The (np.random.shuffle) function allows us to randomly shuffle an array. 
# Note that the shuffling happens in place (i.e. no raturn value), and shuffling muti-dimensional arrays only shuffles the first dimension
vec = np.array([1,2,3,4,5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([3, 4, 2, 5, 1])
array([5, 3, 4, 2, 1])
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])


# C. Distributions

In [22]:
# we can use (np.random.uniform) to draw pseudo- random real numbers from a uniform distribution
# it prints out random probability of an event
print(np.random.uniform()) # default range is [0.0,1.0)
print(np.random.uniform(low = -1.5, high = 2.2))
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low = -3.4, high = 5.9, size = (2,2))))


0.4125388415030261
-1.3735661486123956
array([0.62402999, 0.66063573, 0.29849529])
array([[ 0.74905091, -1.33424171],
       [-2.7177132 ,  0.9639183 ]])


In [3]:
# another popular distribution we can sample from is the normal (Gaussian) distribution. The function we use is (np.random.normal)
print(np.random.normal())
print(np.random.normal(loc = 1.5, scale=3.5))
# here (loc) represents mean, (scale) represents standard deviation
print(repr(np.random.normal(loc=-2.4, scale=4.0, size=(2,2)))) 

1.64473389922641
-5.58278115940801
array([[ 1.45317413, -1.85786379],
       [12.19198979, -5.90545622]])


# D. Custom sampling

In [5]:
colors = ['red', 'blue', 'green']
print(np.random.choice(colors)) # it does a random choice in the given colors and print that one
print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2,2), p =[0.8, 0.19, 0.01])))
# in the above line keyword (p) rsepresents the probabilities of each element in the input distribution
# note thet the list of probabilities for p must sum to 1-

red
array(['green', 'blue'], dtype='<U5')
array([['blue', 'red'],
       ['red', 'red']], dtype='<U5')
