In [2]:
import numpy as np

# A. Array accessing

In [3]:
# accessing array is identical to accesing python list
arr3 = np.array([[[1,2,3,4], [2,3,4,5], [3,4,5,6]], [[4,5,6,7], [5,6,7,8], [6,7,8,9]]])
print(arr3)
print(arr3[0,1,2]) # prints the index 2(of 0d) element of index 1(of 1d) element of index 0(of 2d) element --> 4
print(arr3[0,1]) # prints index 1(of 1d) element of index 0(of 2d) element --> [2 3 4 5]
print(arr3[0]) # prints the index 0(of 2d) element --> [[1 2 3 4]
#                                                       [2 3 4 5]
#                                                       [3 4 5 6]]

[[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]

 [[4 5 6 7]
  [5 6 7 8]
  [6 7 8 9]]]
4
[2 3 4 5]
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


# B. Slicing

In [4]:
# slicing means we are only want some part of array and not a complete aray
arr = np.array([1,2,3,4,5])
print(repr(arr[:])) # it prints complete array
print(repr(arr[1:])) # it starts printing from index (1) and prints complete
print(repr(arr[2:4])) # it starts from index (2) and prints till index (4) (excluding index 4)
print(repr(arr[:-1])) # it prints from index(0) to index(-1 = last index) (excluding last index)
print(repr(arr[-2:])) # it prints from index (-2 = second last) to the end

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


In [8]:
# for multidimensional array we use (,)
arr = np.array([[[1,2,3,4], [2,3,4,5], [3,4,5,6]], [[4,5,6,7], [5,6,7,8], [6,7,8,9]]])
print(repr(arr[:])) # it works on 2nd dimension and prints it's 0th and 1th index (means complete array)
print(repr(arr[1:])) # it works on 2nd dimension and prints from index 1 (means second half part [[4,5,6,7], [5,6,7,8], [6,7,8,9]]) 
print(repr(arr[:, -1])) # before (,) part works on 2nd dimension then after (,) it goes in 1st dimension and print -1th index element of 2nd dimension()
print(repr(arr[:, 1:])) # before (,) part works on 2nd dimension then after (,) it goes in 1st dimension and print from index 1 till last element of each and every 3nd dimension element
print(repr(arr[0:1, 1:])) # before (,) part works on 2nd dimension but only on index 0 of it then go to 1st dimension and start print from index 1 till last element of it
print(repr(arr[0, 1:])) # before (,) part works on 2nd dimension but only go in index 0 of it then go to 1st dimension and start printing it from it's index 1 till it's last index
print(repr(arr[0:1,1,1:3])) # before first (,) part works on 2nd dimension but only go in index 0 of it then go to 1st dimension and only of it's index 1 then go to 0th dimension and start printing from it's index 1 to index 3 (excluding index 3)

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]],

       [[4, 5, 6, 7],
        [5, 6, 7, 8],
        [6, 7, 8, 9]]])
array([[[4, 5, 6, 7],
        [5, 6, 7, 8],
        [6, 7, 8, 9]]])
array([[3, 4, 5, 6],
       [6, 7, 8, 9]])
array([[[2, 3, 4, 5],
        [3, 4, 5, 6]],

       [[5, 6, 7, 8],
        [6, 7, 8, 9]]])
array([[[2, 3, 4, 5],
        [3, 4, 5, 6]]])
array([[2, 3, 4, 5],
       [3, 4, 5, 6]])
array([[3, 4]])


# C. Argmin and argmax

In [9]:
# np.argmin and np.argmax are use to get the index of minimum and maximum value element in an array
arr = np.array([[-2,-1,-3],[4,5,-6],[-3,9,1]])
print(np.argmin(arr[0])) # it gives the index of minimum among 0d elements of 1d 0th index element
print(np.argmax(arr[2])) # it gives the index of maximum among 0d elements of 1d 2nd index element
print(np.argmin(arr)) # it gives the index of minimum element among all the elements of array

2
1
5


In [10]:
# it is also use with (axis) keyword to specifies which dimension to apply the operation
arr = np.array([[-2,-1,-3],[4,5,-6],[-3,9,1]])
print(repr(np.argmin(arr, axis = 0))) # axis 0 means it gives the row index at which value is minimum, for every column
print(repr(np.argmin(arr, axis = 1))) # it gives the column index at which value is minimum, for every row
print(repr(np.argmin(arr, axis = -1))) # axis -1 means last dimension so in our case it is axis 1

array([2, 0, 1], dtype=int64)
array([2, 2, 0], dtype=int64)
array([2, 2, 0], dtype=int64)
