In [1]:
import numpy as np

# A. Analysis
##### We can obtain minimum and maximum values of a NumPy array using its inherent (min) and (max) function. This gives us an initial sense of the data's range, and can alert us to extreme outliers in the data.

In [3]:
arr = np.array([[0,72,3],
                [1,3,-60],
                [-3,-2,4]])
print(arr.min())
print(arr.max())
print(repr(arr.min(axis=0)))
print(repr(arr.max(axis=1)))

-60
72
array([ -3,  -2, -60])
array([72,  3,  4])


# B. Statistical metrics

##### NumPy also provides basic statistical functions such as (np.mean), (np.var), (np.median), to calculate the mean, variance, and median of the data, respetively. 

In [4]:
arr = np.array([[0,72,3],
                [1,3,-60],
                [-3,-2,4]])
print(np.mean(arr))
print(np.var(arr))
print(np.median(arr))
print(repr(np.median(arr,axis = -1)))

2.0
977.3333333333334
1.0
array([ 3.,  1., -2.])
