In [1]:
import numpy as np

# A. Summation
##### To sum the values within a single array, we use the np.sum function.

In [2]:
arr = np.array([[0,72,3],
                [1,3,-60],
                [-3,-2,4]])
print(np.sum(arr)) # it prints the sum of all elements of the array
print(repr(np.sum(arr, axis=0))) # it prints the sum of each column
print(repr(np.sum(arr, axis=1))) # it prints the sum of each rows

18
array([ -2,  73, -53])
array([ 75, -56,  -1])


##### In addition to regular sums, NumPy can perform cumulative sums using (np.cumsum). If the acis keyword argument is not specified , (np.cumsum) will return the cumulative sums for the flattened array.

In [3]:
arr = np.array([[0,72,3],
                [1,3,-60],
                [-3,-2,4]])
print(repr(np.cumsum(arr)))
print(repr(np.cumsum(arr, axis =0)))
print(repr(np.cumsum(arr, axis =1)))

array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])
array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])
array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])


# B. Concatenation

In [4]:
arr1 = np.array([[0,72,3],
                [1,3,-60],
                [-3,-2,4]])
arr2 = np.array([[-15,6,1],
                [8,9,-4],
                [5,-21,18]])
print(repr(np.concatenate([arr1,arr2]))) # by default it concatenate with axis 0 means number of rows will increase
print(repr(np.concatenate([arr1,arr2], axis=1))) # number of column will increase
print(repr(np.concatenate([arr2,arr1], axis=1))) # number of column will increase

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
array([[-15,   6,   1,   0,  72,   3],
       [  8,   9,  -4,   1,   3, -60],
       [  5, -21,  18,  -3,  -2,   4]])
